#!/bin/bash


(
  source ./detect-python
  cd ml-sharp &&
  if [ -z "$( ls -A '../input' )" ]; then
    echo "No files found in the ./input folder, exiting quietly"
    exit 0
  fi
  for file in ../input/*; do
    echo "Current input file is $file"
    BASE=`basename "$file" .jpg` || exit 1
    if [ -f "../output/$BASE.ply" ]; then
      echo "../output/$BASE.ply exists, skipping"
    else
      # Generate splat from photo
      echo "Running the sharp model to create a .ply splat file..."
      time sharp predict -i "$file" -o ../output || exit 1
    fi
    if [ -f "../output/$BASE-reduced.ply" ]; then
      echo "../output/$BASE-reduced.ply exists, skipping"
    else
      # Decimate (adjust --percentage as needed)
      echo "Creating reduced-size version for Quest 3 compatibility..."
      time python Gaussian_Decimator/decimate.py \
        --path_to_model "../output/$BASE.ply" \
        --save_path "../output/$BASE-reduced.ply" || exit 1
    fi
  done
) &&
echo "Conversion complete."

