#!/bin/bash

(
  if [ ! -d "ml-sharp" ]; then
    git clone https://github.com/apple/ml-sharp || exit 1
  fi
  source ./detect-python
  cd ml-sharp &&
  pip install -r requirements.txt &&

  if [ ! -d "Gaussian_Decimator" ]; then
    git clone https://github.com/feel3x/Gaussian_Decimator || exit 1
  fi
  cd Gaussian_Decimator/ &&
  pip install torch-scatter -f https://data.pyg.org/whl/torch-2.8.0+cpu.html &&
  pip install -r requirements.txt &&
  cd ../.. &&
  mkdir -p input &&
  mkdir -p output &&
  echo "Folders created"
) || exit 1

echo "Great! You are ready to put .jpg files in ./input and run ./convert"
